### ISSUE TITLE
Implementing RemoteRead 

### ISSUE THREAD

**Issue by lucavagnozzi** [KasparNagu/PortableDevices#1]
Hi KasparNagu,

I'm sorry it seems I have no other way to contact you...
I saw the "uploadStream" method to upload a file from PC to device.
I'd like to ask you if you think it's possible to write a "downloadStream" method in order to transfer a file from device to the PC.

I'm trying it without success...
I get "Error 0xC0000005 Access violation" when I try to read to a file (I tried with a jpg and with txt files)
Here is an example snippet I'm using in order to read, could you please give it a check an let me know what's wrong with it?

I added the WPD_RESOURCE_DEFAULT definition on PortableDevice.py and added it to propertiesToRead attribute in PortableDeviceContent class.

Then I use the following code to read the file:
```python
path = "Memoria interna/DCIM/Camera/IMG_20161127_144349"
devices = wpd.getPortableDevices()
for device in devices:
    pdContent = device.getContent().getPath(path)
    resources = pdContent.content.Transfer()
    pFileStream = ctypes.POINTER(wpd.port.IStream)()
    optimalTransferSizeBytes = ctypes.pointer(ctypes.c_ulong(0))
    optimalTransferSizeBytes, fileStream = resources.GetStream(
            pdContent.objectID,
            wpd.WPD_RESOURCE_DEFAULT,
            ctypes.c_ulong(0),
            optimalTransferSizeBytes,
            pFileStream
    )
    blockSize = optimalTransferSizeBytes.contents.value
    # I just want to try to read the file content on the line below
    res = fileStream.RemoteRead(ctypes.c_ulong(blockSize))
    # ... code crashes on line above
```

Thank you in advance for any help on this.

**Comment by KasparNagu** [comment]
Hey shakraw

Diving in this code after years took some time, but I finally found the solution. You were of course quite close. The thing is again to mess with the comtypes generated file (see README.md). And then supply the RemoteRead with a buffer to use.

Just commited it. Not heavily tested, but seemed to work for some text files.

Have fun!

**Comment by lucavagnozzi** [comment]
Hi KasparNagu,

thank you, it seems to be ok to me. 
I tested it on copying images (thumbail and original hres resources) from devices/camera to pc, it seems to works.
